

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rds-job-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rds-secret-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rds-secret-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rds-secret-role
subjects:
- kind: ServiceAccount
  name: rds-job-sa


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-rds-config
data:
  main.tf: |
    provider "aws" {
      region = var.aws_region
    }

    variable "aws_region" {
      default = "eu-north-1"
    }

    variable "db_username" {
      type = string
    }

    variable "db_password" {
      type = string
      sensitive = true
    }

    variable "db_identifier" {
      type = string
    }

    resource "aws_db_instance" "default" {
      allocated_storage    = 20
      engine               = "postgres"
      # engine_version       = "13.7"
      instance_class       = "db.t3.micro"
      db_name              = "mydatabase"
      username             = var.db_username
      password             = var.db_password
      # db_subnet_group_name = "subnet-0b0cc2d8b401eae1e" # adjust to your subnet group
      # skip_final_snapshot  = true
      # publicly_accessible  = false
      identifier           = var.db_identifier
    }

    output "endpoint" {
      value = aws_db_instance.default.endpoint
    }

    output "username" {
      value = aws_db_instance.default.username
      sensitive = true
    }

    output "password" {
      value = aws_db_instance.default.password
      sensitive = true
    }

---

apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-rds-secret-job
spec:
  backoffLimit: 100
  template:
    spec:
      serviceAccountName: rds-job-sa
      restartPolicy: Never
      containers:
      - name: terraform
        image: hashicorp/terraform:1.5.0
        workingDir: /workspace
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        command:
        - /bin/sh
        - -c
        - |
          cp /config/main.tf .
          terraform init
          terraform apply -auto-approve \
            -var="db_username=mydbuser" \
            -var="db_password=MySecretPass123" \
            -var="db_identifier=my-rds-instance-1" \
            -var="aws_region=eu-north-1" && \
          terraform output -json > /shared/output.json
        volumeMounts:
        - name: config
          mountPath: /config
        - name: shared
          mountPath: /shared
      - name: create-secret
        image: bitnami/kubectl:latest
        workingDir: /shared
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache jq curl >/dev/null
          while [ ! -f /shared/output.json ]; do sleep 2; done
          echo "Parsing output.json..."
          ENDPOINT=$(jq -r '.endpoint.value' /shared/output.json)
          USERNAME=$(jq -r '.username.value' /shared/output.json)
          PASSWORD=$(jq -r '.password.value' /shared/output.json)

          echo "Creating Kubernetes Secret..."
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: rds-credentials
          type: Opaque
          stringData:
            endpoint: "$ENDPOINT"
            username: "$USERNAME"
            password: "$PASSWORD"
          EOF
        volumeMounts:
        - name: shared
          mountPath: /shared
      volumes:
      - name: config
        configMap:
          name: terraform-rds-config
      - name: shared
        emptyDir: {}
---
