name: RDS Provision via Terraform Job on EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Apply Terraform in EKS Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name kafka-cluster --region $AWS_REGION
      - name: Create AWS Secret in Kubernetes
        run: |
          kubectl delete secret aws-creds-env --ignore-not-found
          kubectl create secret generic aws-credentials \
            --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Delete existing Job (if any)
        run: |
          kubectl delete job terraform-rds-secret-job || true

      - name: Apply Terraform Kubernetes Job
        run: |
          kubectl apply -f terraform-rds-secret-job.yaml
          kubectl get all
          
      - name: Wait for Job completion
        run: |
          kubectl wait --for=condition=complete --timeout=1200s job/terraform-rds-secret-job

      - name: Get logs from Job
        run: |
          POD_NAME=$(kubectl get pods --selector=job-name=terraform-rds-secret-job -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME
